import Head from "next/head";
import Section from "../components/Section";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zimo Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main role="main">
        {/* section 1 */}
        <Section targetId="section2">
          <div className="container relative flex min-h-screen items-center py-16">
            <h1 className="uppercase text-4xl sm:text-5xl md:text-6xl xl:text-7xl font-light tracking-widest">
              zimo group
            </h1>
            <div className="hero-img-wrapper">
              {/* eslint-disable-next-line */}
              <img src="/assets/zimo-black.png" alt="" />
            </div>
          </div>
        </Section>

        {/* section 2 */}
        <Section
          targetId="section3"
          id="section2"
          className="bg-black text-white"
          invertedArrow={true}
        >
          <div className="flex flex-col justify-center gap-8 md:flex-row items-center min-h-screen py-16">
            <Image
              src="/assets/logo2-white.png"
              height={54}
              width={200}
              alt=""
            />
            <div className="text-center mx-auto text-[30px]">
              <p>We are the global platform.</p>
              <p className="mt-3">
                Services in over one hundred and twenty countries.
              </p>
            </div>
          </div>
        </Section>

        {/* section 3 */}
        <Section targetId="section4" id="section3">
          <div className="flex min-h-screen flex-col justify-center py-8">
            <p className="text-[30px] text-center">REVOLUTIONARY</p>

            <div className="flex flex-col md:flex-row my-8 gap-8 justify-around items-center">
              {/* eslint-disable-next-line */}
              <img
                src="/assets/zimo-logo.png"
                alt="zimo"
                className="w-52 md:w-72"
              />
              <div
                style={{ border: "1px solid #BE9F56" }}
                className="h-0 w-52 md:h-[250px] md:w-0"
              />
              {/* eslint-disable-next-line */}
              <img
                src="/assets/zimo-pro.png"
                alt="zimo pro"
                className="w-52 md:w-72"
              />
            </div>

            <p className="text-center text-[30px]">
              {"The only platform of it's kind in the world."}
            </p>
          </div>
        </Section>

        {/* section 4 */}
        <Section
          targetId="section5"
          id="section4"
          className="bg-black"
          invertedArrow={true}
        >
          <div className="min-h-screen py-8">
            <div className="forground-text">
              {/* eslint-disable-next-line */}
              <img src="/assets/section4-texts.png" alt="" />
            </div>

            {/* background img */}
            {/* eslint-disable-next-line */}
            <img
              src="/assets/zimo-group.png"
              alt=""
              className="absolute blur-sm lg:blur-md"
              style={{
                top: "50%",
                left: "50%",
                transform: "translate(-50%, -50%)",
              }}
            />
          </div>
        </Section>

        {/* section 5 real estate */}
        <Section targetId="section6" id="section5" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              real estate
            </h4>
          </div>
        </Section>

        {/* section 6 cars */}
        <Section targetId="section7" id="section6" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              cars
            </h4>
          </div>
          <div className="car-models w-80 md:w-96">
            {/* eslint-disable-next-line */}
            <img src="/assets/cars-model.png" alt="" />
          </div>
        </Section>

        {/* section 7 yatcj */}
        <Section targetId="section8" id="section7" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              YACHTS
            </h4>
          </div>
        </Section>

        {/* section 8 watches */}
        <Section targetId="section9" id="section8" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              Watches
            </h4>
          </div>
        </Section>

        {/* section 9 jets */}
        <Section targetId="section10" id="section9" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              Jets
            </h4>
          </div>
        </Section>

        {/* section 10 private island */}
        <Section targetId="section11" id="section10" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              PRIVATE ISLANDS
            </h4>
          </div>
        </Section>

        {/* section 11 diamond */}
        <Section targetId="section12" id="section11" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              Diamonds
            </h4>
          </div>
        </Section>

        {/* section 12 travel */}
        <Section targetId="section13" id="section12" invertedArrow={true}>
          <div className="overlay z-0" />
          <div className="flex justify-center items-center min-h-screen relative z-10">
            <h4 className="text-[40px] uppercase text-white opacity-50 tracking-wider">
              Travel the world
            </h4>
          </div>
        </Section>

        {/* section 13 last section */}
        <Section id="section13">
          <div
            className="container mx-auto flex flex-col"
            style={{ minHeight: "70vh" }}
          >
            <div className="m-auto">
              <Image
                src="/assets/zdoc.png"
                height={200}
                width={200}
                alt="zdoc."
              />
            </div>
          </div>

          <div className="py-2">
            <p className="text-center text-[20px] md:text-[30px]">
              Document-signing software technology that lets you sign documents
              online.
            </p>

            {/* signatures */}
            <div className="w-[300px] ml-auto mt-8">
              <div className="flex justify-between border-black border-b-2 border-solid pb-4">
                <Image
                  src="/assets/zdoc-arrow.png"
                  alt="zdoc"
                  height={60}
                  width={45}
                />
                <Image
                  src="/assets/signatures.png"
                  alt="zdoc"
                  height={70}
                  width={200}
                />
              </div>
              <small className="text-[8px] float-right">
                ZD:SID 46791269900490374129
              </small>
            </div>
          </div>
        </Section>
      </main>
    </>
  );
}
